-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.622.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 30.12.2013 19:47:11
-- Server version: 5.6.12
-- Client version: 4.1

--
-- Definition for database `university2.0.`
--
DROP DATABASE IF EXISTS `university2.0.`;
CREATE DATABASE `university2.0.`
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Set default database
--
USE `university2.0.`;

--
-- Definition for table `group`
--
CREATE TABLE `group` (
  id int(11) NOT NULL DEFAULT 0,
  amount int(11) DEFAULT NULL,
  curator varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionOrgGroup FOREIGN KEY (id)
  REFERENCES institutionorg (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table buildings
--
CREATE TABLE buildings (
  id int(11) NOT NULL DEFAULT 0,
  rooms int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionBuildings FOREIGN KEY (id)
  REFERENCES institution (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table buildingsother
--
CREATE TABLE buildingsother (
  id int(11) NOT NULL DEFAULT 0,
  `desc` mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT BuildingsBuildingsOther FOREIGN KEY (id)
  REFERENCES buildings (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table cathedra
--
CREATE TABLE cathedra (
  id int(11) NOT NULL DEFAULT 0,
  specialization varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  employees int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionOrgCathedra FOREIGN KEY (id)
  REFERENCES institutionorg (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table chummery
--
CREATE TABLE chummery (
  id int(11) NOT NULL DEFAULT 0,
  comendant varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  faculty mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT BuildingsChummery FOREIGN KEY (id)
  REFERENCES buildings (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table classes
--
CREATE TABLE classes (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  Children mediumtext DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table classes_func
--
CREATE TABLE classes_func (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  Children mediumtext DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table classroom
--
CREATE TABLE classroom (
  id int(11) NOT NULL DEFAULT 0,
  seats int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionClassRoom FOREIGN KEY (id)
  REFERENCES institution (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table clinic
--
CREATE TABLE clinic (
  id int(11) NOT NULL DEFAULT 0,
  amount_cabinets int(11) DEFAULT NULL,
  doctors mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT BuildingsClinic FOREIGN KEY (id)
  REFERENCES buildings (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table collective
--
CREATE TABLE collective (
  id int(11) NOT NULL DEFAULT 0,
  activity varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  amount int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionOrgCollective FOREIGN KEY (id)
  REFERENCES institutionorg (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table deanery
--
CREATE TABLE deanery (
  id int(11) NOT NULL DEFAULT 0,
  assistant mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionOrgDeanery FOREIGN KEY (id)
  REFERENCES institutionorg (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table document
--
CREATE TABLE document (
  id int(11) NOT NULL DEFAULT 0,
  author varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT MaterialObjectDocument FOREIGN KEY (id)
  REFERENCES materialobject (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table documentgeneral
--
CREATE TABLE documentgeneral (
  id int(11) NOT NULL DEFAULT 0,
  doc_type varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT DocumentDocumentGeneral FOREIGN KEY (id)
  REFERENCES document (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table documentother
--
CREATE TABLE documentother (
  id int(11) NOT NULL DEFAULT 0,
  `desc` mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT DocumentDocumentOther FOREIGN KEY (id)
  REFERENCES document (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table documentpersonal
--
CREATE TABLE documentpersonal (
  id int(11) NOT NULL DEFAULT 0,
  number varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT DocumentDocumentPersonal FOREIGN KEY (id)
  REFERENCES document (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table equipment
--
CREATE TABLE equipment (
  id int(11) NOT NULL DEFAULT 0,
  status varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT MaterialObjectEquipment FOREIGN KEY (id)
  REFERENCES materialobject (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table eventcultural
--
CREATE TABLE eventcultural (
  id int(11) NOT NULL DEFAULT 0,
  reason varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT EventsEventCultural FOREIGN KEY (id)
  REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table events
--
CREATE TABLE events (
  id int(11) NOT NULL DEFAULT 0,
  date_action varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  place_action varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT ObjEvents FOREIGN KEY (id)
  REFERENCES obj (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table eventscience
--
CREATE TABLE eventscience (
  id int(11) NOT NULL DEFAULT 0,
  theme varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT EventsEventScience FOREIGN KEY (id)
  REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table eventsport
--
CREATE TABLE eventsport (
  id int(11) NOT NULL DEFAULT 0,
  sport varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  referee varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  status varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT EventsEventSport FOREIGN KEY (id)
  REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table eventtest
--
CREATE TABLE eventtest (
  id int(11) NOT NULL DEFAULT 0,
  max_mark int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT EventScienceEventTest FOREIGN KEY (id)
  REFERENCES eventscience (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table eventwork
--
CREATE TABLE eventwork (
  id int(11) NOT NULL DEFAULT 0,
  type_of_work varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT EventsEventWork FOREIGN KEY (id)
  REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table faculty
--
CREATE TABLE faculty (
  id int(11) NOT NULL DEFAULT 0,
  amount_cathedr int(11) DEFAULT NULL,
  amount_groups int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionOrgFaculty FOREIGN KEY (id)
  REFERENCES institutionorg (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table institution
--
CREATE TABLE institution (
  id int(11) NOT NULL DEFAULT 0,
  adress varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UObjectInstitution FOREIGN KEY (id)
  REFERENCES uobject (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table institutionorg
--
CREATE TABLE institutionorg (
  id int(11) NOT NULL DEFAULT 0,
  chief varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionInstitutionOrg FOREIGN KEY (id)
  REFERENCES institution (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table institutionother
--
CREATE TABLE institutionother (
  id int(11) NOT NULL DEFAULT 0,
  `desc` mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionOrgInstitutionOther FOREIGN KEY (id)
  REFERENCES institutionorg (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table materialobject
--
CREATE TABLE materialobject (
  id int(11) NOT NULL DEFAULT 0,
  date_creation varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT ObjMaterialObject FOREIGN KEY (id)
  REFERENCES obj (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table nomaterialobjother
--
CREATE TABLE nomaterialobjother (
  id int(11) NOT NULL DEFAULT 0,
  `desc` mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT ObjNoMaterialObjOther FOREIGN KEY (id)
  REFERENCES obj (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table obj
--
CREATE TABLE obj (
  id int(11) NOT NULL DEFAULT 0,
  responsible_person varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UObjectObj FOREIGN KEY (id)
  REFERENCES uobject (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table other
--
CREATE TABLE other (
  id int(11) NOT NULL DEFAULT 0,
  `desc` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UObjectOther FOREIGN KEY (id)
  REFERENCES uobject (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table othermaterialobject
--
CREATE TABLE othermaterialobject (
  id int(11) NOT NULL DEFAULT 0,
  `desc` mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT MaterialObjectOtherMaterialObject FOREIGN KEY (id)
  REFERENCES materialobject (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table painting
--
CREATE TABLE painting (
  id int(11) NOT NULL DEFAULT 0,
  brush varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table person
--
CREATE TABLE person (
  id int(11) NOT NULL DEFAULT 0,
  sex varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  birthday varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UObjectPerson FOREIGN KEY (id)
  REFERENCES uobject (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table personentrants
--
CREATE TABLE personentrants (
  id int(11) NOT NULL DEFAULT 0,
  zno_points int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT PersonStudingPersonEntrants FOREIGN KEY (id)
  REFERENCES personstuding (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table persongraduatestudent
--
CREATE TABLE persongraduatestudent (
  id int(11) NOT NULL DEFAULT 0,
  years int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT PersonTeachingPersonGraduateStudent FOREIGN KEY (id)
  REFERENCES personteaching (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table personother
--
CREATE TABLE personother (
  id int(11) NOT NULL DEFAULT 0,
  benefit mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT PersonPersonOther FOREIGN KEY (id)
  REFERENCES person (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table personstudents
--
CREATE TABLE personstudents (
  id int(11) NOT NULL DEFAULT 0,
  studing_form varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  entry_year int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT PersonStudingPersonStudents FOREIGN KEY (id)
  REFERENCES personstuding (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table personstuding
--
CREATE TABLE personstuding (
  id int(11) NOT NULL DEFAULT 0,
  secondary_education varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT PersonPersonStuding FOREIGN KEY (id)
  REFERENCES person (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table personteachers
--
CREATE TABLE personteachers (
  id int(11) NOT NULL DEFAULT 0,
  academic_degree varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT PersonTeachingPersonTeachers FOREIGN KEY (id)
  REFERENCES personteaching (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table personteaching
--
CREATE TABLE personteaching (
  id int(11) NOT NULL DEFAULT 0,
  subject mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT PersonWorkingPersonTeaching FOREIGN KEY (id)
  REFERENCES personworking (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table personworkers
--
CREATE TABLE personworkers (
  id int(11) NOT NULL DEFAULT 0,
  post varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT PersonWorkingPersonWorkers FOREIGN KEY (id)
  REFERENCES personworking (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table personworking
--
CREATE TABLE personworking (
  id int(11) NOT NULL DEFAULT 0,
  experience varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  salary varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT PersonPersonWorking FOREIGN KEY (id)
  REFERENCES person (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table process
--
CREATE TABLE process (
  id int(11) NOT NULL DEFAULT 0,
  start varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  end varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  person_vyk varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table rectorat
--
CREATE TABLE rectorat (
  id int(11) NOT NULL DEFAULT 0,
  prorectors mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionOrgRectorat FOREIGN KEY (id)
  REFERENCES institutionorg (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table remont
--
CREATE TABLE remont (
  id int(11) NOT NULL DEFAULT 0,
  materials mediumtext DEFAULT NULL,
  suma int(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table subject
--
CREATE TABLE subject (
  id int(11) NOT NULL DEFAULT 0,
  teachers mediumtext DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT ObjSubject FOREIGN KEY (id)
  REFERENCES obj (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table territory
--
CREATE TABLE territory (
  id int(11) NOT NULL DEFAULT 0,
  area varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionTerritory FOREIGN KEY (id)
  REFERENCES institution (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table transport
--
CREATE TABLE transport (
  id int(11) NOT NULL DEFAULT 0,
  number varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  type varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  price int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT MaterialObjectTransport FOREIGN KEY (id)
  REFERENCES materialobject (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table universities
--
CREATE TABLE universities (
  id int(11) NOT NULL DEFAULT 0,
  accredetation varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT InstitutionOrgUniversities FOREIGN KEY (id)
  REFERENCES institutionorg (id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Definition for table uobject
--
CREATE TABLE uobject (
  id int(11) NOT NULL DEFAULT 0,
  major int(11) DEFAULT NULL,
  name varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  class int(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;